---
title: "Fly Mating: evolution rate figs"
author: "Aram Avila-Herrera"
date: "`r date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    highlight: pygments
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = '#>')
```

# Load per-base scores and annotation

Computed in [methods](./methods.html), tabulated by [mktbl.R](./scripts/mktbl.R)

```{r, message = FALSE}
library(tidyverse)
library(magrittr)
library(vcd)
library(pander)

scores <- read_tsv("./results/phylop.tsv")

# quick visual check of brower vs local phylop
plot(select(scores, browser_LRT_all, LRT_all))
```

Convenience functions...

```{r}
# scores are -log p-values: negative for accel, positive for cons
score2p <- function(s){
    10^(-sign(s) * s)
}
```

Plotting functions:

```{r}
plot_histogram <- function(scores_df, test_scores, fill_color = "#3fa9f5", bins = 10){
  ggplot(scores_df) + geom_histogram(
    aes_string(x = test_scores),
    fill = fill_color,
    color = "grey20",
    bins = bins
  ) +
  xlab("PhyloP score") +
  theme_classic()
}
```

## melanogaster branch test

```{r, include = FALSE, eval = FALSE}
count(scores, score2p(LRT_dmel) < 0.01)
mel_hist = ggplot(scores) + geom_histogram(aes(x = score2p(LRT_dmel)),
                                           fill = '#3fa9f5',
                                           color = 'grey20',
                                           breaks = seq(0,1,by=0.02)
                                           ) +
    #scale_y_continuous(breaks = seq(0, 125, 25)) +
    scale_y_continuous(breaks = seq(0, 1000, 200)) +
    geom_vline(xintercept = 0.01, linetype = 'dashed', color = 'grey20') +
    #coord_cartesian(ylim = c(0,230)) +
    coord_cartesian(ylim = c(0,1005)) +
    ggtitle("PhyloP test for non-neutral evolution on dm6") +
    xlab("p-value") +
    ylab(expression(paste("# of ", italic("D. mel"), " Bases"))) +
    theme_classic()
#ggsave(plot = mel_hist, 'dm6-phylop-hist-661.pdf')
ggsave(plot = mel_hist, 'figs/dm6-phylop-hist-3.7k.pdf')
mel_hist
```

```{r}
mel_hist <- plot_histogram(scores, "LRT_dmel", bins = 30) +
  ylab(expression(paste("# of ", italic("D. mel"), " Bases")))
mel_hist
mel_hist + facet_wrap(~isCDS, labeller = label_both)
mel_hist + facet_wrap(~isIntron, labeller = label_both)
mel_hist + facet_wrap(~isUTR5|isUTR3, labeller = label_both)
mel_hist + facet_grid(isConsEl~isIntrgn, labeller = label_both)
```

## simulans branch test

```{r}
sim_hist <- plot_histogram(scores, "LRT_dsim", fill_color = "#ff1d25", bins = 30) +
  ylab(expression(paste("# of ", italic("D. sim"), " Bases")))
sim_hist + facet_wrap(~isCDS, labeller = label_both)
sim_hist + facet_wrap(~isIntron, labeller = label_both)
sim_hist + facet_wrap(~isUTR5|isUTR3, labeller = label_both)
sim_hist + facet_grid(isConsEl~isIntrgn, labeller = label_both)
```

## All-branches test

```{r}
allbr_hist <- plot_histogram(scores, "LRT_all", fill_color = "#68409c", bins = 30) +
  ylab("# of 27way alignment columns")
allbr_hist + facet_wrap(~isCDS, labeller = label_both)
allbr_hist + facet_wrap(~isIntron, labeller = label_both)
allbr_hist + facet_wrap(~isUTR5|isUTR3, labeller = label_both)
allbr_hist + facet_grid(isConsEl~isIntrgn, labeller = label_both)
```

### counts of accelerated sites

- A score of 2 corresponds to P-value of 0.01
- Negative := acceleration
- Positive := conservation

```{r, results = "asis"}
sigcounts <- scores %>%
  count(
    LRT_all < -2, LRT_dmel < -2, LRT_dsim < -2,
    isConsEl
)
knitr::kable(sigcounts)
pander(ftable(xtabs(n ~ ., sigcounts)), style = "rmarkdown")
```

# Load per-feature tests

```{r, message = FALSE}
ftr_fns <- list.files(path="reg_3.7/phylop", pattern = "-phylop27-ftr-\\w+\\.tsv", full.names = TRUE)
ftr_tbl <- lapply(ftr_fns, read_tsv) %>%
  setNames(., nm = sub("\\..*$", "", basename(ftr_fns))) %>%
  bind_rows(.id = "fn")
ftr_tbl %<>%
  separate(fn, c("Branch", "Feature"), "-phylop27-ftr-")
ftr_tbl %>% select(Branch, Feature, pval)
```

